from PIL import Image

def rgb(hex_string):
    return tuple(int(hex_string[i:i+2], 16) for i in (1, 3, 5)) + (255,)

ADVENTURER_PALETTE = {
    "k": "#1b1b2a", "h": "#3a6b8c", "H": "#5a93b5", "c": "#2b4f69",
    "s": "#e8b796", "S": "#c48f70", "e": "#1b1b2a", "b": "#6b4a2b",
    "p": "#4a3b5c", "B": "#3b2a1b", "w": "#c8d0d8", "g": "#d0a040",
}
GOBLIN_PALETTE = {
    "k": "#1a2016", "G": "#6aa84f", "D": "#4a7a38", "L": "#93c96f",
    "y": "#f2d34a", "e": "#1a2016", "t": "#f0f0e0", "l": "#7a5230",
    "m": "#56391f", "n": "#8a6a3a", "w": "#c8d0d8",
}

ADVENTURER_FRONT_RIGHT = """
................
................
................
.....kkkkkk.....
....khHHHhhk....
...khHHhhhhhk.w.
...khhssssssk.w.
...khhsseseSk.w.
...khhsssssSk.w.
....khhhsssk..w.
...kchhhhhhhk.w.
..kcchhhhHhhhkw.
..kcchhhhhhhsggg
..kcsbbbbbbbbkb.
..kcchhhhhhhhk..
..kcchhhhhhhhk..
...kcpppppppk...
...kkppppppkk...
....kppkkppk....
....kppkkppk....
....kppkkppk....
....kBBkkBBBk...
...kBBBkkBBBBk..
...kkkkkkkkkkk..
"""

ADVENTURER_RIGHT = """
................
................
................
.....kkkkk......
....khHHHhk..w..
...khHHhhhhk.w..
...khhhhhssk.w..
...khhhhhsek.w..
...khhhhsssskw..
....khhhhssk.w..
....kchhhhhk.w..
...kcchhHhhkggg.
...kcchhhhhkss..
...kcbbbbbbk.b..
...kcchhhhhk....
...kcchhhhhk....
....kcppppk.....
....kppppppk....
...kppk..kppk...
...kppk..kppk...
..kppk....kppk..
..kBBk....kBBk..
.kBBBk....kBBBBk
.kkkkk....kkkkkk
"""

ADVENTURER_BACK_RIGHT = """
................
................
................
.....kkkkkk.....
....khHHHHhk....
...khHHHhhhhk...
...khHhhhhhhk...
...khhhhhhhsk.w.
...khhhhhhhsk.w.
....khhhhhhk..w.
...kcccccccck.w.
..kcccHcccccckw.
..kccccccccccggg
..kcbbbbbbbbckb.
..kccccccccccck.
..kccccccccccck.
...kcppppppck...
...kkppppppkk...
....kppkkppk....
....kppkkppk....
....kppkkppk....
....kBBkkBBk....
...kBBBkkBBBk...
...kkkkkkkkkk...
"""

GOBLIN_FRONT_RIGHT = """
................
................
................
................
................
................
....kkkkkkk.....
...kLLLGGGGk....
k.kLLGGGGGGGk.k.
kGkGGGyeGGyeGkGk
.kGGGGGGGDGGGGk.
..kGGGGGGDDGGk..
...kGGttkttGk...
....kkGGGGkk....
...kmllllllmk...
..kGmllllllmGk..
..kGkllllllkGk..
..kkmlllllmkkn..
...kmmmmmmmk.w..
....kGGkkGGk.w..
....kGGkkGGk....
....kDDkkDDDk...
...kDDDkkDDDDk..
...kkkkkkkkkkk..
"""

GOBLIN_RIGHT = """
................
................
................
................
................
................
................
....kkkkkk......
...kLLLGGGk.....
kk.kLGGGGGyek...
kGkGGGGGGGGGGk..
.kGGGGGGGGGDDDk.
..kGGGGGGGttk...
...kkGGGGGkk....
....kmlllmk.....
....kmlllmGk....
....kmlllmGnww..
....kmmmmmk.....
....kGGkGGk.....
...kGGk.kGGk....
...kGGk.kGGk....
..kDDk...kDDk...
.kDDDk...kDDDDk.
.kkkkk...kkkkkk.
"""

GOBLIN_BACK_RIGHT = """
................
................
................
................
................
................
................
....kkkkkkk.....
...kGGGGGGGk....
k.kGGGGGGGGGk..k
kGkGGGGGGGGGkkGk
.kGGDGGGGGGGGk..
..kGGGGGGGGGk...
...kkGGGGGkk....
...kmmmmmmmk....
..kGmmmlmmmGk...
..kGkmmmmmkGnk..
...kmmmmmmmk.w..
...kmmmmmmmk.w..
....kGGkkGGk....
....kGGkkGGk....
....kDDkkDDk....
...kDDDkkDDDk...
...kkkkkkkkkk...
"""

def render(ascii_art, palette):
    rows = [row for row in ascii_art.strip("\n").split("\n")]
    assert len(rows) == 24, len(rows)
    image = Image.new("RGBA", (16, 24), (0, 0, 0, 0))
    for y, row in enumerate(rows):
        assert len(row) == 16, (y, len(row), row)
        for x, symbol in enumerate(row):
            if symbol != ".":
                image.putpixel((x, y), rgb(palette[symbol]))
    return image

def mirror(image):
    return image.transpose(Image.FLIP_LEFT_RIGHT)

def build_sheet(front_right, right, back_right, palette):
    # Frame order = hexgrid.Direction order, as seen on screen:
    # East, North_East, North_West, West, South_West, South_East
    front_right, right, back_right = render(front_right, palette), render(right, palette), render(back_right, palette)
    frames = [right, back_right, mirror(back_right), mirror(right), mirror(front_right), front_right]
    sheet = Image.new("RGBA", (16 * 6, 24), (0, 0, 0, 0))
    for index, frame in enumerate(frames):
        sheet.paste(frame, (index * 16, 0))
    return sheet

if __name__ == "__main__":
    adventurer = build_sheet(ADVENTURER_FRONT_RIGHT, ADVENTURER_RIGHT, ADVENTURER_BACK_RIGHT, ADVENTURER_PALETTE)
    goblin = build_sheet(GOBLIN_FRONT_RIGHT, GOBLIN_RIGHT, GOBLIN_BACK_RIGHT, GOBLIN_PALETTE)
    adventurer.save("adventurer_sheet.png")
    goblin.save("goblin_sheet.png")
    preview = Image.new("RGBA", (96, 50), (40, 44, 58, 255))
    preview.alpha_composite(adventurer, (0, 0))
    preview.alpha_composite(goblin, (0, 26))
    preview.resize((96 * 8, 50 * 8), Image.NEAREST).save("/tmp/sheets_preview.png")
    print("ok")
